stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build_after_push:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${MY_REGISTRY_USER}:${MY_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --destination "${MY_REGISTRY}/komaroffski/ng-app:${CI_COMMIT_SHORT_SHA}"

build_after_tagged:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  only:
  - tags
  except:
  - branches
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${MY_REGISTRY_USER}:${MY_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --destination "${MY_REGISTRY}/komaroffski/ng-app:${CI_COMMIT_TAG}"
    - >-
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --destination "${MY_REGISTRY}/komaroffski/ng-app:$latest"

deploy_after_tagged:
  stage: deploy
  only:
  - tags
  except:
  - branches
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl apply -f ${CI_PROJECT_DIR}/deployment/
    - kubectl delete pod -n ng-app -l app=nginx-app-stage