FROM nginx:latest
RUN rm -rf /usr/share/nginx/html/*
RUN mkdir -p /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
COPY ./images/bull.jpg /usr/share/nginx/html/images/
COPY ./images/franch.jpg /usr/share/nginx/html/images/
COPY ./images/korgy.jpg /usr/share/nginx/html/images/