apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app-stage
  name: nginx-app-stage
  namespace: ng-app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-app-stage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-app-stage
    spec:
      containers:
      - image: docker.io/komaroffski/ng-app:latest
        imagePullPolicy: Always
        name: nginx-app-stage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
